import type { Question } from "./types";

// 乐理题库种子数据
// 每个题目字段：category, type, difficulty, content, options(选择题), answer, explanation
// 选择题 answer 为选项索引（0-based）字符串；判断题 answer 为 "true"/"false"；填空题 answer 为标准答案文本

interface SeedQuestion
  extends Omit<Question, "id" | "options" | "image_url"> {
  options: string[] | null;
  image_url?: string | null;
}

export const SEED_QUESTIONS: SeedQuestion[] = [
  // ============ 音程 interval ============
  {
    category: "interval",
    type: "choice",
    difficulty: "easy",
    content: "从 C 到 G 的音程名称是？",
    options: ["纯四度", "纯五度", "大三度", "小六度"],
    answer: "1",
    explanation: "C-D-E-F-G 共 5 个音级，且为完全协和音程，故为纯五度。",
  },
  {
    category: "interval",
    type: "choice",
    difficulty: "easy",
    content: "从 C 到 E 的音程是？",
    options: ["小三度", "大三度", "纯四度", "增三度"],
    answer: "1",
    explanation: "C-D-E 三个音级，包含两个全音（4 个半音），为大三度。",
  },
  {
    category: "interval",
    type: "choice",
    difficulty: "medium",
    content: "从 D 到 F 的音程是？",
    options: ["大三度", "小三度", "减三度", "纯四度"],
    answer: "1",
    explanation: "D-E-F 三个音级，D-E 为全音、E-F 为半音，共 3 个半音，为小三度。",
  },
  {
    category: "interval",
    type: "choice",
    difficulty: "medium",
    content: "增四度包含几个半音？",
    options: ["4 个", "5 个", "6 个", "7 个"],
    answer: "2",
    explanation: "增四度（三全音）包含 6 个半音，例如 F-B。",
  },
  {
    category: "interval",
    type: "fill",
    difficulty: "easy",
    content: "纯八度包含 ____ 个半音。",
    options: null,
    answer: "12",
    explanation: "一个八度平均分为 12 个半音。",
  },
  {
    category: "interval",
    type: "fill",
    difficulty: "medium",
    content: "大三度包含 ____ 个半音。",
    options: null,
    answer: "4",
    explanation: "大三度 = 两个全音 = 4 个半音。",
  },
  {
    category: "interval",
    type: "judge",
    difficulty: "easy",
    content: "纯五度是协和音程。",
    options: null,
    answer: "true",
    explanation: "纯一度、纯八度、纯四度、纯五度均为完全协和音程。",
  },
  {
    category: "interval",
    type: "judge",
    difficulty: "medium",
    content: "小七度是协和音程。",
    options: null,
    answer: "false",
    explanation: "大小三度、大小六度为不完全协和；大小二七度、增减音程为不协和音程。小七度属于不协和音程。",
  },
  {
    category: "interval",
    type: "choice",
    difficulty: "hard",
    content: "将大三度缩小一个半音后变为？",
    options: ["小三度", "减三度", "增三度", "纯三度"],
    answer: "0",
    explanation: "大三度缩小半音音数减少，度数不变，变为小三度。",
  },
  {
    category: "interval",
    type: "choice",
    difficulty: "hard",
    content: "音程 C-♭E 的名称是？",
    options: ["大三度", "小三度", "减三度", "增二度"],
    answer: "1",
    explanation: "C 到 E 为大三度，降 E 缩小半音，变为小三度（3 个半音）。",
  },

  // ============ 和弦 chord ============
  {
    category: "chord",
    type: "choice",
    difficulty: "easy",
    content: "大三和弦的结构（从低到高）是？",
    options: ["大三度+小三度", "小三度+大三度", "小三度+小三度", "大三度+大三度"],
    answer: "0",
    explanation: "大三和弦 = 大三度 + 小三度（根音到三音大三度，三音到五音小三度）。",
  },
  {
    category: "chord",
    type: "choice",
    difficulty: "easy",
    content: "C 大三和弦由哪三个音组成？",
    options: ["C E G", "C ♭E G", "C E ♯G", "C E A"],
    answer: "0",
    explanation: "C 大三和弦 = 根音 C + 大三度 E + 纯五度 G。",
  },
  {
    category: "chord",
    type: "choice",
    difficulty: "medium",
    content: "小三和弦的结构是？",
    options: ["大三度+小三度", "小三度+大三度", "小三度+小三度", "大三度+大三度"],
    answer: "1",
    explanation: "小三和弦 = 小三度 + 大三度。",
  },
  {
    category: "chord",
    type: "choice",
    difficulty: "medium",
    content: "属七和弦（大小七和弦）的结构是？",
    options: [
      "大三和弦+大三度",
      "大三和弦+小三度",
      "小三和弦+小三度",
      "减三和弦+减三度",
    ],
    answer: "1",
    explanation: "属七和弦 = 大三和弦 + 小七度（即根音到七音为小七度，三音到七音为纯五度），结构可表述为大三和弦上方叠小三度。",
  },
  {
    category: "chord",
    type: "choice",
    difficulty: "hard",
    content: "减七和弦由哪些音程叠置而成？",
    options: [
      "小三度+小三度+小三度",
      "大三度+小三度+小三度",
      "小三度+大三度+小三度",
      "减三度+小三度+小三度",
    ],
    answer: "0",
    explanation: "减七和弦 = 减三和弦 + 减七度，相邻音均为小三度，即连续三个小三度叠置。",
  },
  {
    category: "chord",
    type: "fill",
    difficulty: "easy",
    content: "三和弦由根音、三音和 ____ 构成。",
    options: null,
    answer: "五音",
    explanation: "三和弦由根音、三音、五音按三度关系叠置而成。",
  },
  {
    category: "chord",
    type: "fill",
    difficulty: "medium",
    content: "G7 和弦的四个音是 G、B、D、____。",
    options: null,
    answer: "F",
    explanation: "G7 为属七和弦，根音 G，三音 B，五音 D，七音 F（小七度）。",
  },
  {
    category: "chord",
    type: "judge",
    difficulty: "easy",
    content: "增三和弦的五音比纯五度高半音。",
    options: null,
    answer: "true",
    explanation: "增三和弦 = 大三度 + 大三度，五音比纯五度高半音（增五度）。",
  },
  {
    category: "chord",
    type: "judge",
    difficulty: "medium",
    content: "大小七和弦就是属七和弦。",
    options: null,
    answer: "true",
    explanation: "大小七和弦（大三和弦+小七度）在调式中作属七和弦使用，两者所指相同。",
  },
  {
    category: "chord",
    type: "choice",
    difficulty: "hard",
    content: "C 大七和弦（Cmaj7）的七音是？",
    options: ["B♭", "B", "A", "C"],
    answer: "1",
    explanation: "大七和弦为大三和弦加大七度，C 到 B 为大七度，故七音为 B。",
  },

  // ============ 调式调性 mode ============
  {
    category: "mode",
    type: "choice",
    difficulty: "easy",
    content: "C 大调的调号有几个升降号？",
    options: ["0 个", "1 个升号", "1 个降号", "2 个升号"],
    answer: "0",
    explanation: "C 大调没有升降号，是最基础的大调。",
  },
  {
    category: "mode",
    type: "choice",
    difficulty: "easy",
    content: "G 大调的调号是？",
    options: ["1 个升号（F♯）", "1 个降号（B♭）", "2 个升号", "无升降号"],
    answer: "0",
    explanation: "G 大调有一个升号 F♯。",
  },
  {
    category: "mode",
    type: "choice",
    difficulty: "medium",
    content: "a 小调的关系大调是？",
    options: ["C 大调", "G 大调", "F 大调", "D 大调"],
    answer: "0",
    explanation: "a 小调与 C 大调调号相同（无升降号），互为关系大小调。",
  },
  {
    category: "mode",
    type: "choice",
    difficulty: "medium",
    content: "F 大调的调号包含哪个降号？",
    options: ["B♭", "E♭", "A♭", "D♭"],
    answer: "0",
    explanation: "F 大调有一个降号 B♭。",
  },
  {
    category: "mode",
    type: "choice",
    difficulty: "hard",
    content: "D 大调有几个升号？",
    options: ["1 个", "2 个", "3 个", "4 个"],
    answer: "1",
    explanation: "D 大调有 F♯ 和 C♯ 两个升号。",
  },
  {
    category: "mode",
    type: "fill",
    difficulty: "easy",
    content: "大调的音阶音程结构（全/半）是：全全半全全全 ____。",
    options: null,
    answer: "半",
    explanation: "大调音阶结构为 全全半全全全半。",
  },
  {
    category: "mode",
    type: "fill",
    difficulty: "medium",
    content: "e 小调的关系大调是 ____ 大调。",
    options: null,
    answer: "G",
    explanation: "e 小调与 G 大调调号相同（一个升号 F♯）。",
  },
  {
    category: "mode",
    type: "judge",
    difficulty: "easy",
    content: "关系大小调的调号相同。",
    options: null,
    answer: "true",
    explanation: "关系大小调共用同一调号，主音相差小三度。",
  },
  {
    category: "mode",
    type: "judge",
    difficulty: "medium",
    content: "小调的主音与其关系大调的主音相同。",
    options: null,
    answer: "false",
    explanation: "关系大小调主音不同，小调主音在大调主音下方小三度。",
  },
  {
    category: "mode",
    type: "choice",
    difficulty: "hard",
    content: "和声小调升高第 VII 级音的目的是？",
    options: [
      "使音阶更流畅",
      "形成导音到主音的倾向，增强终止感",
      "降低难度",
      "与大调一致",
    ],
    answer: "1",
    explanation: "和声小调升高 VII 级形成导音，解决到主音倾向更强，增强终止感。",
  },

  // ============ 节奏节拍 rhythm ============
  {
    category: "rhythm",
    type: "choice",
    difficulty: "easy",
    content: "一个全音符等于几个四分音符？",
    options: ["2 个", "4 个", "8 个", "16 个"],
    answer: "1",
    explanation: "全音符 = 2 二分 = 4 四分 = 8 八分 = 16 十六分。",
  },
  {
    category: "rhythm",
    type: "choice",
    difficulty: "easy",
    content: "4/4 拍中，一小节共有几拍？",
    options: ["2 拍", "3 拍", "4 拍", "6 拍"],
    answer: "2",
    explanation: "4/4 拍表示以四分音符为一拍，每小节 4 拍。",
  },
  {
    category: "rhythm",
    type: "choice",
    difficulty: "medium",
    content: "附点四分音符的时值等于？",
    options: ["1 拍", "1.5 拍", "2 拍", "3 拍"],
    answer: "1",
    explanation: "附点延长原音符时值的一半，四分音符（1 拍）+ 附点（0.5 拍）= 1.5 拍。",
  },
  {
    category: "rhythm",
    type: "choice",
    difficulty: "medium",
    content: "3/4 拍的强弱规律是？",
    options: ["强弱弱", "强弱强弱", "强强弱", "弱强强"],
    answer: "0",
    explanation: "3/4 拍为单拍子，强弱规律是 强-弱-弱。",
  },
  {
    category: "rhythm",
    type: "fill",
    difficulty: "easy",
    content: "一个二分音符等于 ____ 个四分音符。",
    options: null,
    answer: "2",
    explanation: "二分音符时值为 2 拍（四分音符为一拍时）。",
  },
  {
    category: "rhythm",
    type: "fill",
    difficulty: "medium",
    content: "6/8 拍属于 ____ 拍子。",
    options: null,
    answer: "复",
    explanation: "6/8 拍由两个 3/8 组成，属于复拍子，强弱规律为 强弱弱 次强弱弱。",
  },
  {
    category: "rhythm",
    type: "judge",
    difficulty: "easy",
    content: "在 4/4 拍中，一个全音符占满整个小节。",
    options: null,
    answer: "true",
    explanation: "全音符等于 4 拍，在 4/4 拍中正好占满一小节。",
  },
  {
    category: "rhythm",
    type: "judge",
    difficulty: "medium",
    content: "切分音会改变原有节拍的强弱规律。",
    options: null,
    answer: "true",
    explanation: "切分音通过把强拍位置的音延到弱拍，打破原有强弱规律，产生重音转移。",
  },
  {
    category: "rhythm",
    type: "choice",
    difficulty: "hard",
    content: "三连音是将基本音符均分为几部分来代替原来的几部分？",
    options: ["二代三", "三代二", "四代三", "三代四"],
    answer: "1",
    explanation: "三连音把一个基本音符均分为三部分来代替原来的两部分（三代二）。",
  },
  {
    category: "rhythm",
    type: "choice",
    difficulty: "hard",
    content: "2/2 拍中一个全音符等于几拍？",
    options: ["1 拍", "2 拍", "4 拍", "8 拍"],
    answer: "1",
    explanation: "2/2 拍以二分音符为一拍，全音符 = 2 个二分音符 = 2 拍。",
  },

  // ============ 乐谱识读 notation ============
  {
    category: "notation",
    type: "choice",
    difficulty: "easy",
    content: "高音谱号又叫？",
    options: ["G 谱号", "F 谱号", "C 谱号", "D 谱号"],
    answer: "0",
    explanation: "高音谱号（G 谱号）以二线为 G 音。",
  },
  {
    category: "notation",
    type: "choice",
    difficulty: "easy",
    content: "低音谱号又叫？",
    options: ["G 谱号", "F 谱号", "C 谱号", "D 谱号"],
    answer: "1",
    explanation: "低音谱号（F 谱号）以四线为 F 音。",
  },
  {
    category: "notation",
    type: "choice",
    difficulty: "medium",
    content: "高音谱表中，第二间的音是？",
    options: ["A", "B", "C", "D"],
    answer: "0",
    explanation: "高音谱表线：E G B D F，间：F A C E。第二间为 A。",
  },
  {
    category: "notation",
    type: "choice",
    difficulty: "medium",
    content: "高音谱表中，上加一线的音是？",
    options: ["A", "B", "C", "D"],
    answer: "1",
    explanation: "高音谱表第五线为 F，上加一间为 G，上加一线为 A。注：中央 C 在高音谱表下加一线。",
  },
  {
    category: "notation",
    type: "choice",
    difficulty: "hard",
    content: "低音谱表中，中央 C 位于？",
    options: ["下加一线", "上加一线", "第一线", "第四线"],
    answer: "1",
    explanation: "中央 C 在低音谱表上加一线（与高音谱表下加一线为同一音）。",
  },
  {
    category: "notation",
    type: "fill",
    difficulty: "easy",
    content: "高音谱表下加一线的音是 ____（音名）。",
    options: null,
    answer: "C",
    explanation: "高音谱表下加一线为中央 C。",
  },
  {
    category: "notation",
    type: "fill",
    difficulty: "medium",
    content: "高音谱表第五线的音名是 ____。",
    options: null,
    answer: "F",
    explanation: "高音谱表线音名为 E G B D F（Every Good Boy Does Fine），第五线为 F。",
  },
  {
    category: "notation",
    type: "judge",
    difficulty: "easy",
    content: "中音谱号属于 C 谱号。",
    options: null,
    answer: "true",
    explanation: "中音谱号（C 谱号）以三线为中央 C。",
  },
  {
    category: "notation",
    type: "judge",
    difficulty: "medium",
    content: "高音谱表与低音谱表联合构成大谱表。",
    options: null,
    answer: "true",
    explanation: "大谱表由高音谱表和低音谱表通过连谱号连接而成，中间以中央 C 衔接。",
  },
  {
    category: "notation",
    type: "choice",
    difficulty: "hard",
    content: "变音记号中，还原记号的作用是？",
    options: [
      "升高半音",
      "降低半音",
      "取消升/降记号，回到本位音",
      "升高全音",
    ],
    answer: "2",
    explanation: "还原记号（♮）取消之前的升降记号，使该音回到本位。",
  },

  // ============ 音乐术语与记号 terms ============
  {
    category: "terms",
    type: "choice",
    difficulty: "easy",
    content: "力度记号 f 表示？",
    options: ["弱", "强", "中弱", "极强"],
    answer: "1",
    explanation: "f（forte）表示强。",
  },
  {
    category: "terms",
    type: "choice",
    difficulty: "easy",
    content: "速度术语 Allegro 的意思是？",
    options: ["慢板", "行板", "快板", "广板"],
    answer: "2",
    explanation: "Allegro 意为快板，速度约 120-168 BPM。",
  },
  {
    category: "terms",
    type: "choice",
    difficulty: "medium",
    content: "力度记号 p 表示？",
    options: ["强", "中强", "弱", "很弱"],
    answer: "2",
    explanation: "p（piano）表示弱。",
  },
  {
    category: "terms",
    type: "choice",
    difficulty: "medium",
    content: "术语 cresc. (crescendo) 表示？",
    options: ["渐弱", "渐强", "渐慢", "突强"],
    answer: "1",
    explanation: "crescendo 表示渐强。",
  },
  {
    category: "terms",
    type: "choice",
    difficulty: "hard",
    content: "术语 Andante 的意思是？",
    options: ["快板", "行板", "慢板", "急板"],
    answer: "1",
    explanation: "Andante 意为行板，速度约 76-108 BPM。",
  },
  {
    category: "terms",
    type: "fill",
    difficulty: "easy",
    content: "力度记号 ff 表示 ____。",
    options: null,
    answer: "很强",
    explanation: "ff（fortissimo）表示很强。",
  },
  {
    category: "terms",
    type: "fill",
    difficulty: "medium",
    content: "记号 \"8va\" 表示 ____ 八度演奏。",
    options: null,
    answer: "高",
    explanation: "8va（ottava）表示提高八度演奏。",
  },
  {
    category: "terms",
    type: "judge",
    difficulty: "easy",
    content: "延长记号（𝄐）表示该音根据需要自由延长时值。",
    options: null,
    answer: "true",
    explanation: "延长记号（Fermata）表示按乐曲需要适当延长时值。",
  },
  {
    category: "terms",
    type: "judge",
    difficulty: "medium",
    content: "D.C. 表示从记号处反复。",
    options: null,
    answer: "false",
    explanation: "D.C.（Da Capo）表示从头反复；D.S. 才表示从记号处反复。",
  },
  {
    category: "terms",
    type: "choice",
    difficulty: "hard",
    content: "演奏记号 staccato（断奏）的效果是？",
    options: ["连贯圆滑", "短促跳跃", "渐强", "保持时值"],
    answer: "1",
    explanation: "断奏记号使音符演奏得短促、跳跃，实际时值缩短。",
  },
];
